version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-4.10"
python:
  install:
    - method: pip
      path: ./python/ipywidgets
    - method: pip
      path: ./python/jupyterlab_widgets
conda:
  environment: docs/environment.yml

# python:
#     version: 3.7
#     install:
#       - method: pip
#         path: ./python/ipywidgets
#       - requirements: docs/requirements.txt
