nodeLinker: node-modules
enableImmutableInstalls: false

# prettier-ignore
packageExtensions:
  "@nrwl/devkit@^15":
    dependencies:
      nx: ^15
  postcss-cssnext@^3.1.0:
    dependencies:
      caniuse-lite: ^1
  source-map-loader@^4:
    dependencies:
      webpack: ^5

enableTelemetry: false

httpTimeout: 60000

# these messages provide no actionable information, and make non-TTY output
# almost unreadable, masking real dependency-related information
# see: https://yarnpkg.com/advanced/error-codes
logFilters:
  - code: YN0006 # SOFT_LINK_BUILD
    level: discard
  - code: YN0007 # MUST_BUILD
    level: discard
  - code: YN0008 # MUST_REBUILD
    level: discard
  - code: YN0013 # FETCH_NOT_CACHED
    level: discard
  - code: YN0019 # UNUSED_CACHE_ENTRY
    level: discard
